[package]
name = "shor"
version = "0.0.2"
license = "MIT"
authors = ["itsubaki"]
description = "Shor's factoring algorithm written in rust"
repository = "https://github.com/itsubaki/shor"
edition = "2018"

[dependencies]
rand = "0.8.4"
num = "0.4.0"
