[package]
name = "shor"
version = "0.0.3"
license = "MIT"
authors = ["itsubaki"]
description = "Shor's factoring algorithm written in rust"
repository = "https://github.com/itsubaki/shor"
edition = "2018"

[dependencies]
q-rs = "0.0.1"
