[package]
name = "shor"
version = "1.0.0"
license = "MIT"
authors = ["itsubaki"]
description = "Shor's factoring algorithm written in rust"
edition = "2018"

[dependencies]
rand = "0.8.4"
num = "0.4.0"
